### ISSUE TITLE
Request specification overrides port from base url

### ISSUE THREAD

**Issue by johanhaleby** [rest-assured/rest-assured#533]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on December 07, 2014 14:57:54_

I am using a RequestSpecification to specify the accept and content-type headers. I do not set the port in the request spec.

When using a non default port and setting the baseURI port 80 seems to  be used from the request specification.

When setting the requestContentType and responseContentType (with the deprecated setters) and not using the request specification it works as expected.

I suggest to either un-deprecate the setter and make a documentation note the request specification or merge the configuration from baseURI and request specification.

_Original issue: http://code.google.com/p/rest-assured/issues/detail?id=378_

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on December 30, 2014 01:04:37_

This is probably a bug in the merging of request specifications

**Status:** Accepted

**Comment by johanhaleby** [comment]
_From [johan.ha...@gmail.com](https://code.google.com/u/105676376875942041029/) on March 17, 2015 04:39:05_

I'm trying to reproduce this but I can't. You you provide a code example of your test?

**Comment by johanhaleby** [comment]
_From [everf...@gmail.com](https://code.google.com/u/100456722887713625293/) on March 17, 2015 04:46:06_

I assume this was fixed in the mean time, I switched to request spec and could not rep produce the issue.

**Comment by luv** [comment]
Still an issue in 2.9.0.
```
RestAssured.baseURI = "http://localhost:81"
RestAssured.requestContentType(ContentType.JSON)
// makes request to example.com port 81
RestAssured.get("http://example.com")
```

the behaviour of requestContentType is actually way more fucked than just this ....

**Comment by luv** [comment]
I see requestContentType is deprecated though - what is the recommended substitute?

**Comment by johanhaleby** [comment]
See javadoc.
